Add missing distutils to fix builds on some architectures
Like arm32v7 and arm32v6

```
  File "/var/lib/ghost/versions/5.104.2/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'
```